package no.nav.helse.flex.sykepengesoknad.kafka

enum class InntektskildetypeDTO {
    ANDRE_ARBEIDSFORHOLD,
    FRILANSER,
    SELVSTENDIG_NARINGSDRIVENDE,
    SELVSTENDIG_NARINGSDRIVENDE_DAGMAMMA,
    JORDBRUKER_FISKER_REINDRIFTSUTOVER,
    ANNET,
    FOSTERHJEMGODTGJORELSE,
    OMSORGSLONN,
    ARBEIDSFORHOLD,
    FRILANSER_SELVSTENDIG,
    STYREVERV,
}
