package no.nav.syfo.kafka.sykepengesoknadarbeidsledig.dto

enum class InntektskildetypeDTO {
    ANDRE_ARBEIDSFORHOLD,
    FRILANSER,
    SELVSTENDIG_NARINGSDRIVENDE,
    SELVSTENDIG_NARINGSDRIVENDE_DAGMAMMA,
    JORDBRUKER_FISKER_REINDRIFTSUTOVER,
    OMSORGSLONN,
    FOSTERHJEMGODTGJORELSE,
    ANNET
}
