package no.nav.syfo.kafka.felles

enum class InntektskildetypeDTO {
    ANDRE_ARBEIDSFORHOLD,
    FRILANSER,
    SELVSTENDIG_NARINGSDRIVENDE,
    SELVSTENDIG_NARINGSDRIVENDE_DAGMAMMA,
    JORDBRUKER_FISKER_REINDRIFTSUTOVER,
    ANNET
}
