name: Publish artifacts
on:
  push:
jobs:
  build_and_release:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Generer versjon
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=8 HEAD)
          VERSION=$TIME-$COMMIT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Setup gradle dependency cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Lint
        run: ./gradlew ktlintCheck
      - name: test and build
        run: ./gradlew -Pversion="$(echo $VERSION)" build
      - name: upload artifact
        if: github.ref_name == 'main'
        run: ./gradlew -Pversion="$(echo $VERSION)" publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
